# Machine-specific accent color for prompt/tmux identity.
# Set THEME_COLOR in ~/.zshrc.local (blue default; also red|green|purple|yellow|orange|teal).
if [[ -r "$HOME/.scripts/theme.lib.sh" ]]; then
  . "$HOME/.scripts/theme.lib.sh"
  theme_load_palette "${THEME_COLOR:-}"
fi

typeset -g POWERLEVEL9K_DIR_BACKGROUND="${DOTFILES_THEME_DIR_BG:-25}"
typeset -g POWERLEVEL9K_DIRENV_BACKGROUND="${DOTFILES_THEME_DIRENV_BG:-25}"
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND="${DOTFILES_THEME_VCS_LOADING_BG:-24}"
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND="${DOTFILES_THEME_PROMPT_OK_FG:-39}"

if (( ${+functions[p10k]} )); then
  p10k reload
fi

unset DOTFILES_THEME_DIR_BG DOTFILES_THEME_DIRENV_BG DOTFILES_THEME_VCS_LOADING_BG
unset DOTFILES_THEME_PROMPT_OK_FG DOTFILES_THEME_TMUX_ACCENT_BG DOTFILES_THEME_TMUX_MODE_BG
unset DOTFILES_THEME_TMUX_CLOCK DOTFILES_THEME_HEX_ACCENT DOTFILES_THEME_HEX_ACCENT_SOFT
unset DOTFILES_THEME_HEX_BORDER DOTFILES_THEME_ANSI_ACCENT
